In [1]:
import numpy as np
import pandas as pd

In [2]:
temp_df=pd.read_csv("../dataset/IMDB Dataset.csv")

In [3]:
df=temp_df.iloc[:1000]

In [4]:
df.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


In [5]:
df["sentiment"].value_counts()

sentiment
positive    501
negative    499
Name: count, dtype: int64

In [6]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
# Basic Text Preprocessing
# Removing HTML tags
# lowercasing
# Removing stop words

In [9]:
import re
def remove_html_tags(text):
    clean = re.sub(re.compile('<.*?>'), '', text)
    return clean

In [10]:
df['review'] = df['review'].apply(remove_html_tags)

In [11]:
df.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. The filming tec...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


In [12]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
def remove_stop_words(text):
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return ' '.join(filtered_words)

In [13]:

df['review'] = df['review'].apply(remove_stop_words)

In [14]:
df

,review,sentiment
0,One reviewers mentioned watching 1 Oz episode ...,positive
1,wonderful little production. filming technique...,positive
2,thought wonderful way spend time hot summer we...,positive
3,Basically there's family little boy (Jake) thi...,negative
4,"Petter Mattei's ""Love Time Money"" visually stu...",positive
...,...,...
995,"Nothing sacred. ask Ernie Fosselius. days, eve...",positive
996,hated it. hate self-aware pretentious inanity ...,negative
997,usually try professional constructive criticiz...,negative
998,like going see film history class something li...,negative


In [15]:
X=df.iloc[:,0:1]
y=df['sentiment']

In [16]:
X

,review
0,One reviewers mentioned watching 1 Oz episode ...
1,wonderful little production. filming technique...
2,thought wonderful way spend time hot summer we...
3,Basically there's family little boy (Jake) thi...
4,"Petter Mattei's ""Love Time Money"" visually stu..."
...,...
995,"Nothing sacred. ask Ernie Fosselius. days, eve..."
996,hated it. hate self-aware pretentious inanity ...
997,usually try professional constructive criticiz...
998,like going see film history class something li...


In [17]:
y

0      positive
1      positive
2      positive
3      negative
4      positive
         ...   
995    positive
996    negative
997    negative
998    negative
999    negative
Name: sentiment, Length: 1000, dtype: str

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [19]:
y

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [21]:
X_train.shape

(800, 1)

In [22]:
# Appy Bow
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_train_cv = cv.fit_transform(X_train['review']).toarray()
X_test_cv = cv.transform(X_test['review']).toarray()

In [23]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train_cv, y_train)

,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)number of training samples observed in each class.","ndarray[float64](2,)","[395.,405.]"
"class_prior_ class_prior_: ndarray of shape (n_classes,)probability of each class.","ndarray[float64](2,)","[0.49,0.51]"
"classes_ classes_: ndarray of shape (n_classes,)class labels known to the classifier.","ndarray[int64](2,)","[0,1]"
epsilon_ epsilon_: floatabsolute additive value to variances.,float64,5.112e-09
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,16077
"theta_ theta_: ndarray of shape (n_classes, n_features)mean of each feature per class.","ndarray[float64](2, 16077)","[[0.01,0.02,0. ,...,0. ,0. ,0. ], [0. ,0.01,0. ,...,0. ,0. ,0. ]]"
"var_ var_: ndarray of shape (n_classes, n_features)Variance of each feature per class... versionadded:: 1.0","ndarray[float64](2, 16077)","[[0.01,0.02,0. ,...,0. ,0. ,0. ], [0. ,0.01,0. ,...,0. ,0. ,0. ]]"


In [24]:
y_pred = gnb.predict(X_test_cv)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.565


In [25]:
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred))

confusion_matrix:
 [[55 49]
 [38 58]]


In [26]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100, random_state=42)
rfc.fit(X_train_cv, y_train)
y_pred_rfc = rfc.predict(X_test_cv)
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rfc))

Random Forest Accuracy: 0.77


In [27]:
cv=CountVectorizer(ngram_range=(1, 2))
X_train_cv = cv.fit_transform(X_train['review']).toarray()
X_test_cv = cv.transform(X_test['review']).toarray()
rfc.fit(X_train_cv, y_train)
y_pred_rfc = rfc.predict(X_test_cv) 
print("Random Forest Accuracy with n-grams:", accuracy_score(y_test, y_pred_rfc))

Random Forest Accuracy with n-grams: 0.82


# Tf-idf

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(ngram_range=(1, 2))
X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review']).toarray()
rfc.fit(X_train_tfidf, y_train)
y_pred_rfc_tfidf = rfc.predict(X_test_tfidf)
print("Random Forest Accuracy with TF-IDF:", accuracy_score(y_test, y_pred_rfc_tfidf))

Random Forest Accuracy with TF-IDF: 0.785


In [30]:
import gensim
from nltk import sent_tokenize, word_tokenize
from gensim.utils import simple_preprocess

In [31]:
story=[]
for doc in df['review']:
    row_sent=sent_tokenize(doc)
    for sent in row_sent:
        story.append(simple_preprocess(sent, deacc=True))

In [32]:
model=gensim.models.Word2Vec(story, vector_size=100, window=5, min_count=1, workers=4)

In [33]:
model.build_vocab(story, progress_per=1000)

In [34]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(597985, 621105)

In [35]:
len(model.wv.index_to_key)

17648

In [44]:
import numpy as np

def document_vector(doc):
    words = [w for w in doc.split() if w in model.wv]

    if len(words) == 0:
        return np.zeros(model.vector_size)

    return np.mean(model.wv[words], axis=0)

In [45]:
count = 0

for review in df['review']:
    words = [w for w in review.split()
             if w in model.wv.index_to_key]

    if len(words) == 0:
        count += 1

print(count)

1


In [46]:
document_vector(df['review'][0])

array([-4.7462156e-01,  8.7156814e-01,  2.7317789e-01,  2.8684759e-01,
       -9.6762672e-02, -1.2492498e+00,  5.3093660e-01,  1.8352294e+00,
       -6.7037094e-01, -6.2719148e-01, -3.6227977e-01, -1.2746757e+00,
       -2.1526983e-01,  3.7248039e-01,  3.1033498e-01, -4.3135625e-01,
        2.2851066e-01, -9.2307603e-01,  2.6482111e-01, -1.7011904e+00,
        5.1803720e-01,  2.8990212e-01,  4.3508020e-01, -4.3660423e-01,
       -4.1209128e-01, -1.3167633e-03, -4.9501142e-01, -3.3013934e-01,
       -9.9467647e-01,  4.5008242e-02,  9.5828325e-01, -2.0690031e-01,
        2.1055950e-01, -2.9143268e-01, -3.4773925e-01,  6.2888998e-01,
        3.3918232e-01, -6.0514325e-01, -6.0039771e-01, -1.3553230e+00,
        1.8858366e-01, -6.9782060e-01, -5.4207516e-01,  7.7122726e-02,
        6.9994491e-01, -1.8380086e-01, -7.9061133e-01, -1.0251647e-01,
        5.3429312e-01,  5.6106305e-01,  3.3221355e-01, -8.5311520e-01,
       -5.4391772e-01, -2.9767252e-04, -4.9719375e-01,  5.3471708e-01,
      

In [48]:
from tqdm import tqdm

In [49]:
X=[]
for doc in tqdm(df['review']):
    X.append(document_vector(doc))

  0%|          | 0/1000 [00:00<?, ?it/s]

100%|██████████| 1000/1000 [00:00<00:00, 4897.47it/s]


In [50]:
X=np.array(X)

In [51]:
X.shape

(1000, 100)

In [52]:
y

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,

In [55]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100, random_state=42)
rfc.fit(X, y)
y_pred_rfc = rfc.predict(X)
accuracy_score(y, y_pred_rfc)

1.0